//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Animals.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnimalsEntities : DbContext
    {
        public AnimalsEntities()
            : base("name=AnimalsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Analysis_of_urine> Analysis_of_urines { get; set; }
        public virtual DbSet<Anamne> Anamnes { get; set; }
        public virtual DbSet<Bacteriological_research> Bacteriological_researches { get; set; }
        public virtual DbSet<Biochemical_analysis_of_blood> Biochemical_analysis_of_bloods { get; set; }
        public virtual DbSet<Common_analysis_of_blood> Common_analysis_of_bloods { get; set; }
        public virtual DbSet<Coprogram__test> Coprogram__tests { get; set; }
        public virtual DbSet<Diagnostic> Diagnostics { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<Microscopy> Microscopies { get; set; }
        public virtual DbSet<Owner> Owners { get; set; }
        public virtual DbSet<Pet> Pets { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Surgical_treatment> Surgical_treatments { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TemperatureList> TemperatureLists { get; set; }
        public virtual DbSet<Treatment> Treatments { get; set; }
        public virtual DbSet<UZI> UZIs { get; set; }
        public virtual DbSet<XRay> XRays { get; set; }
    }
}
