//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Animals.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_analysis_of_blood
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> PetId { get; set; }
        public Nullable<decimal> Leikocit { get; set; }
        public Nullable<decimal> Eritroc { get; set; }
        public Nullable<decimal> Hemoglob { get; set; }
        public Nullable<decimal> Gematocrit { get; set; }
        public Nullable<decimal> KolVoTrombocitov { get; set; }
        public Nullable<decimal> KolVoTrombocitovManual { get; set; }
        public Nullable<decimal> NeitrofiluSegmentPerc { get; set; }
        public Nullable<decimal> NeitrofiluSegmentAbsolut { get; set; }
        public Nullable<decimal> NeitrofiluPalochkoyadPer { get; set; }
        public Nullable<decimal> NeitrofiluPalochkoyadAbsolut { get; set; }
        public Nullable<decimal> LimfocituPerc { get; set; }
        public Nullable<decimal> LimfocituAbsolut { get; set; }
        public Nullable<decimal> MonocituPerc { get; set; }
        public Nullable<decimal> MonocituAbsolut { get; set; }
        public Nullable<decimal> EozinofiluPerc { get; set; }
        public Nullable<decimal> EozinofiluAbsolut { get; set; }
        public Nullable<decimal> BazofiluPerc { get; set; }
        public Nullable<decimal> BazofiluAbsolut { get; set; }
        public Nullable<decimal> RetikulocituPerc { get; set; }
        public Nullable<decimal> RetikulocituKorrectPerc { get; set; }
        public Nullable<decimal> RetikulocituAbsolut { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Pet Pet { get; set; }
    }
}
