//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Animals.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        public Pet()
        {
            this.Analysis_of_urine = new HashSet<Analysis_of_urine>();
            this.Anamnes = new HashSet<Anamne>();
            this.Bacteriological_research = new HashSet<Bacteriological_research>();
            this.Biochemical_analysis_of_blood = new HashSet<Biochemical_analysis_of_blood>();
            this.Common_analysis_of_blood = new HashSet<Common_analysis_of_blood>();
            this.Coprogram__tests = new HashSet<Coprogram__test>();
            this.Diagnostics = new HashSet<Diagnostic>();
            this.Microscopies = new HashSet<Microscopy>();
            this.Photos = new HashSet<Photo>();
            this.Surgical_treatments = new HashSet<Surgical_treatment>();
            this.TemperatureLists = new HashSet<TemperatureList>();
            this.Treatments = new HashSet<Treatment>();
            this.UZIs = new HashSet<UZI>();
            this.XRays = new HashSet<XRay>();
        }
    
        public System.Guid Id { get; set; }
        public string Nickname { get; set; }
        public string PType { get; set; }
        public string Species { get; set; }
        public string Age { get; set; }
        public bool Gender { get; set; }
        public bool Castration { get; set; }
        public bool Vaccination { get; set; }
        public bool Deworming { get; set; }
        public bool Treatment__parasites { get; set; }
        public System.Guid OwnerId { get; set; }
        public System.Guid DoctorId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ICollection<Analysis_of_urine> Analysis_of_urine { get; set; }
        public virtual ICollection<Anamne> Anamnes { get; set; }
        public virtual ICollection<Bacteriological_research> Bacteriological_research { get; set; }
        public virtual ICollection<Biochemical_analysis_of_blood> Biochemical_analysis_of_blood { get; set; }
        public virtual ICollection<Common_analysis_of_blood> Common_analysis_of_blood { get; set; }
        public virtual ICollection<Coprogram__test> Coprogram__tests { get; set; }
        public virtual ICollection<Diagnostic> Diagnostics { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual ICollection<Microscopy> Microscopies { get; set; }
        public virtual Owner Owner { get; set; }
        public virtual ICollection<Photo> Photos { get; set; }
        public virtual ICollection<Surgical_treatment> Surgical_treatments { get; set; }
        public virtual ICollection<TemperatureList> TemperatureLists { get; set; }
        public virtual ICollection<Treatment> Treatments { get; set; }
        public virtual ICollection<UZI> UZIs { get; set; }
        public virtual ICollection<XRay> XRays { get; set; }
    }
}
